#!/usr/bin/env python3
import sys
import os

_src_dir = "%s/src/" % os.path.dirname(os.path.realpath(__file__))
_file_path = os.path.dirname(sys.argv[0])
sys.path.append(os.path.join(_file_path, _src_dir))


if sys.version_info[0] == 3:

    if __name__ == "__main__":
        from fund_my_watcard import main

        main()
else:

    print("Python3 is required, try to run this script by using 'python3 watcard'.")
