#!/usr/bin/env python3
import os
import sys

_src_dir = "%s/fund_my_watcard/" % os.path.dirname(os.path.realpath(__file__))
_file_path = os.path.dirname(sys.argv[0])
sys.path.append(os.path.join(_file_path, _src_dir))

if sys.version_info[0] == 3:
    import fund_my_watcard

    if __name__ == "__main__":
        fund_my_watcard.main()
else:
    from fund_my_watcard import report_error

    report_error("Python3 is required, try to run this script by using 'python3 watcard'.")
